### PR TITLE
Secret::equals()

### PR DESCRIPTION
**Pull request by thekid**
```php
// Current
if ($password === $secret->reveal()) { ... }

// or, better:
if (hash_equals($secret->reveal(), $password)) { ... }

// New
if ($secret->equals($password)) { ... }
```

See also https://wiki.php.net/rfc/timing_attack

### CODE REVIEW

**Comment by thekid** [comment]
This could be backported to 8.X for easy adoption

**Comment by thekid** [comment]
This should be backported to XP8 for easy adoption

**Comment by thekid** [comment]
Not 100% happy with the word `matches()`, as it really tests for equality...  However, `equals()` - overwrites lang.Object::equals(), hrm - while we *are* getting rid of this in favor of lang.Value (and compareTo()), it might be a bit confusing...

https://www.merriam-webster.com/thesaurus/equal#

**Comment by mikey179** [comment]
Maybe `isEqualTo()`?

```
if ($secret->isEqualTo($password)) { ... }
```

**Comment by DavidBruchmann** [comment]
`equals() - overwrites lang.Object::equals(), hrm`

Is there something wrong with the namespaces?

**Comment by thekid** [comment]
> Is there something wrong with the namespaces?

I'm not sure I understand this correctly - but reusing the `equals()` method for another meaning is the problem; there's no *technical* issue here. Usually, `equals()` tests for equality of two objects, and is **true** when two objects of the same class and an *equal* member set. Here, we're testing for equality of a `util.Secret` instance to string primitives that match their *internal* wrapped representation. It's two different concepts mapping to one methods, which I think has potential for confusion.

**Comment by DavidBruchmann** [comment]
mhm, lang.Object and $secret are two very different things and both related classes can have their own equal-Method if required.

**Pull request merged**
